# Generated by Django 4.0.6 on 2022-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traduccion_de_verbos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traduccion_uno', models.CharField(max_length=40)),
                ('traduccion_dos', models.CharField(max_length=40)),
                ('form_verbo_traducido', models.CharField(max_length=40)),
                ],
        ),
    ]
