# Generated by Django 4.0.6 on 2022-08-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_italiano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion_de_verbos',
            name='verbo',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
